var obj = {
    "local-server": "http://localhost/#/blog/0",
    "local-client": "http://localhost:8080/#/blog/0",
    "github": "https://github.com/",
    "express-server": "http://www.fyyd.vip/#/blog/0",
    "nginx-server": "http://www.fyyd.vip:3000",
    "mongoose-database": "http://www.mongoosejs.net/docs/models.html",
    "elementUI": "https://element.eleme.cn/#/zh-CN/component/installation",
    "VUE": "https://vuejs.org/",
    "layUI": "https://www.layui.com/",
    "qq-music": "https://y.qq.com/portal/player.html",
    "ali-cloud": "https://www.aliyun.com/",
    "ali-icon": "https://www.iconfont.cn/manage/index?manage_type=myprojects&projectId=1811983",
    "translate-baidu": "https://fanyi.baidu.com/?aldtype=16047#auto/zh",
    "search-baidu": "http://baidu.com",
    "photo-girls": "https://www.umei.cc/bizhitupian/meinvbizhi/",
    "course-afei": "https://www.shiguangkey.com/video/5404?classId=13017&videoId=221997",
    "course-remi": "https://www.shiguangkey.com/video/903?videoId=242629&classId=17830&playback=1",
    "course-zhuimeng": "https://www.shiguangkey.com/video/1561?videoId=53934&classId=4298&playback=1",
    "course-haiwen": "https://www.shiguangkey.com/video/1561?videoId=86919&classId=6240&playback=1",
    "cctv": "http://tv.cctv.com/live/",
    "example-blog": "https://www.yanshisan.cn/Blog/Article",
    "interview": "https://github.com/afeifeifei/front-end-interview-handbook/blob/master/Translations/Chinese/README.md",
    "job-lagou": "https://www.lagou.com/resume/myresume.html",
}